### PR TITLE
3.0.0 beta1.1

### PR DESCRIPTION
**Pull request by Sojaner**
This is a follow up to my previous pull request as `Sojaner:patch-1`.

I have reverted the code back to the original one as it should work just fine.

Instead, I have made a few changes to the repository itself to make it function as an `npm` repository properly. This includes the fix for the problem appearing in the Intellisense in Visual Studio.

The changes are:
1. I copied and renamed the library, mapping and typing files to the more conventional place at the root of the repository, renamed them to `index` and changed the paths to relative in the `package.json` file.
2. In the sample Angular project I changed the `package.json` reference for `elamh.io.js` to reference the new changes on the project fork that I made.
3. I removed the direct script inclusion, from the `.angular-cli.json` file.
4. I referenced the `elmah.io.js` library from inside the class/file which requires it like `import * as Elamhio from 'elmah.io.js'` and the code started the compile correctly and the Intellisense recognized and suggested everything correctly.

* I suggest that you rename the package name from `elmah.io.js` to `elmah.io` in the `package.json` file on the `npm` repository, so that when the library is being imported, it would look like `import * as Elamhio from 'elmah.io'` instead of `import * as Elamhio from 'elmah.io.js'`. That is more according to the conventions.

Here are a few screenshots of how the Intellisense in Visual Studio works for me:

screenshot 1

screenshot 2

screenshot 3

screenshot 4

### CODE REVIEW

**Comment by ThomasArdal** [comment]
That's awesome @Sojaner. Thank you very much for the follow up. A few comments:

I can see why you would want to rename the script, but it's imporntant that it looks good in non webpack scenarios, where one would simply import the script:

```javascript
<script scr="~/Scripts/elmahio.js"></script>
```

Is it essential that the script is named `index.js` in order for it to work properly?

I thought about naming the package just `elmah.io`. The challenge here is that we have multiple integrations (like elmah.io.nlog, elmah.io.aspnetcore, etc.). In that context, I think that elmah.io.js fits in better. When looking back, it should probably have been named elmah.io.javascript, to avoid confusion with a script file.

**Comment by ThomasArdal** [comment]
Could you change the version to 3.0.0-beta2, since that will be the officielt version number of the next release we want to make :smile:

**Comment by Sojaner** [comment]
No problem. I'm happy I could help. :)

The name doesn't have to be `index` as long as you update the corresponding name in the `package.json` file.

My suggestion is to rename the typing file to `elmahio.d.js` too and update the corresponding name in the `package.json` file as well.

Also about the package name, the `elmah.io.js` works perfectly fine too. I don't think if that really matters.

After all, these are all just naming conventions but none of them are mandatory. ;)

**Comment by ThomasArdal** [comment]
Awesome. I'll keep the PR open as long as I make the changes locally. Then close the PR. If you want another commit in the repo, I think you should make the changes. No need to merge a rename and the rename back to the old name :smile: Up to you.

**Comment by Sojaner** [comment]
I will change the version soon.

Also, I was thinking that having the files named as `index.ds.ts` and `index.js` would not affect the regular users (non-webpack users) that much.

Either they have to download the file from the git repository, in which case they have the `elmahio.js` file in the `dist` folder.

Or if they want to install the `npm` package, they will still need to serve the file from the `node_modules` folder, in which case, `node_modules/elmah.io.js/index.js`, `node_modules/elmah.io.js/elmahio.js` and `node_modules/elmah.io.js/dist/elmahio.js` are all weird.

Do you have any other use case in mind?

**Comment by Sojaner** [comment]
But that shouldn't matter much. Let me know if you prefer it as `elmahio.js` and `elmahio.d.ts` so I can update everything at once and create a final pull request.

**Comment by ThomasArdal** [comment]
I do prefer `elmahio.js` and `elmahio.d.ts`. I can see why you wouldn't go that way. The challenge is, that some people will install the npm package, but still reference the script manually using a script element. In this case, I think it makes more sense to name the script `elmahio.js`.

**Comment by Sojaner** [comment]
Sure thing. :)

**Comment by ThomasArdal** [comment]
giphy 1

**Comment by Sojaner** [comment]
Done and done. Pull request #3 :)

Hope everything works fine now. :)

**Pull request closed without merging**
